version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT}  # Pass PORT from .env to Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Map host:container ports
    environment:
      - DB_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DB}
      - PORT=${PORT}  # Pass PORT to the app at runtime
    restart: unless-stopped