name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
          docker build ./backend --file Dockerfile --tag ghcr.io/htbo/htbo-backend:0.1
          docker login ghcr.io -u htbo -p ${{secrets.GHCR_TOKEN}}
          docker push ghcr.io/htbo/htbo-backend:0.1
